# Generated by Django 4.0.5 on 2022-07-06 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfoStepTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('employment', models.CharField(choices=[('SELF_EMPLOYED', 'self employed'), ('UNEMPLOYED', 'unemployed'), ('PERMANENT', 'permanent'), ('PRIVATE_PRACTICE', 'private practice'), ('PART_TIME', 'part time'), ('CONTRACT', 'contract'), ('OTHER', 'other')], max_length=50)),
                ('income', models.CharField(choices=[('LESS_THAN_5000', 'less than 5000'), ('5001_10000', '5001-10,000'), ('10001_15000', '10001-15000'), ('150001_25000', '150001-25000'), ('25001_40000', '25001-40000'), ('40001_70000', '40001-70000'), ('70001_150000', '70001-150000'), ('ABOVE_150000', 'above 150000')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Info Step Two',
                'verbose_name_plural': 'Personal Info Step Two',
                'db_table': 'step_two',
            },
        ),
    ]
