# Generated by Django 4.0.5 on 2022-07-06 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfoStepOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('idnumber', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=50)),
                ('dateofbirth', models.DateField()),
                ('status', models.CharField(choices=[('SINGLE', 'single'), ('MARRIED', 'married'), ('DIVORCED', 'divorced'), ('WIDOWED', 'widowed'), ('OTHER', 'other')], max_length=50)),
                ('education', models.CharField(choices=[('PRIMARY_SCHOOL', 'primary school'), ('HIGH_SCHOOL', 'high school'), ('CERTIFICATE', 'certificate'), ('DIPLOMA', 'diploma'), ('GRADUATE', 'graduate'), ('POST_GRADUATE', 'post graduate')], max_length=50)),
                ('resident', models.CharField(choices=[('RESIDENT', 'resident'), ('NON_RESIDENT', 'non resident')], max_length=50)),
                ('is_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Info Step One',
                'verbose_name_plural': 'Personal Info Step One',
                'db_table': 'step_one',
            },
        ),
    ]
